version: '2'
services:
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - ./mysqldata:/var/lib/mysql:rw,delegated
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "symfony"
            MYSQL_USER: "symfony"
            MYSQL_PASSWORD: "symfony"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1

    myadmin:
         image: phpmyadmin/phpmyadmin
         ports:
             - "8080:80"
         depends_on:
             - db

    php:
        build: ./php-fpm
        ports:
            - "9000:9000"
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/logs:cached
        links:
            - db
        extra_hosts:
            - "docker.host:127.0.0.1"
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
    elk:
        image: willdurand/elk
        ports:
            - "81:80"
        volumes:
            - ./elk/logstash:/etc/logstash:cached
            - ./elk/logstash/patterns:/opt/logstash/patterns:cached
        volumes_from:
            - php
            - nginx
